const IMG_LIST = {
  formBg: '../../img/pic_bg@2x.png',
  aboutBg: '../../img/pic_bg.png',
  defaultAvatar: '../../img/avatar.png',
  pink1: '../../img/icon_good_p@2x.png',
  pink0: '../../img/icon_good_d@2x.png',
  more: '../../img/icon_more@2x.png',
  num1: '../../img/icon_no1@2x.png',
  num2: '../../img/icon_no2@2x.png',
  num3: '../../img/icon_no3@2x.png',
  name: '../../img/icon_name@2x.png',
  phone: '../../img/icon_phone@2x.png',
  address: '../../img/icon_address@2x.png',
  record: '../../img/icon_record.png',
  list: '../../img/list.png',
  title: '../../img/pic_title@2x.png',
  userbg: '../../img/pic_userbg@2x.png',
  star: '../../img/star.png',
  mapTitle: '../../img/map_title.png',
  medal1: '../../img/medal11.png',
  medalUnlock1: '../../img/medal11.png',
  medal2: '../../img/medal11.png',
  medalUnlock2: '../../img/medal11.png',
  medal3: '../../img/medal11.png',
  medalUnlock3: '../../img/medal11.png',
  medal4: '../../img/medal11.png',
  medalUnlock4: '../../img/medal11.png',
  medal5: '../../img/medal11.png',
  medalUnlock5: '../../img/medal11.png',
  medal6: '../../img/medal11.png',
  medalUnlock6: '../../img/medal11.png',
  medal7: '../../img/medal11.png',
  medalUnlock7: '../../img/medal11.png',
  prize1: '../../img/prize1.png',
  prize2: '../../img/prize2.png',
  prize3: '../../img/prize3.jpeg',
}

module.exports = {
  IMG_LIST
}